<!DOCTYPE html>
<html>
<head>
    <title>Survey Insight Report</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 20px; }
        .survey-title { font-size: 24px; color: #4f46e5; margin-bottom: 5px; }
        .kpi-container { margin-top: 30px; }
        .kpi-card { display: inline-block; width: 30%; border: 1px solid #ddd; padding: 15px; border-radius: 8px; margin-right: 2%; text-align: center; }
        .kpi-name { font-size: 12px; text-transform: uppercase; color: #666; margin-bottom: 10px; }
        .kpi-value { font-size: 24px; font-weight: bold; }
        .section-title { font-size: 18px; border-left: 4px solid #4f46e5; padding-left: 10px; margin-top: 40px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #eee; padding: 10px; text-align: left; }
        th { bg-color: #f9fafb; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="survey-title">{{ $survey->title }}</h1>
        <p>Survey Insight Report - Generated on {{ now()->format('d M Y') }}</p>
    </div>

    <div class="kpi-container">
        @foreach($kpis as $kpi)
            <div class="kpi-card">
                <div class="kpi-name">{{ $kpi->kpi_name }}</div>
                <div class="kpi-value">
                    {{ is_numeric($kpi->kpi_value) ? number_format($kpi->kpi_value, 1) : $kpi->kpi_value }}
                </div>
            </div>
        @endforeach
    </div>

    <h2 class="section-title">Response Distribution</h2>
    <table>
        <thead>
            <tr>
                <th>Answer / Score</th>
                <th>Total Responses</th>
            </tr>
        </thead>
        <tbody>
            @foreach($distribution as $item)
                <tr>
                    <td>{{ $item->answer }}</td>
                    <td>{{ $item->total }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Survey Details</h2>
    <p><strong>Total Questions:</strong> {{ $survey->questions->count() }}</p>
    <p><strong>Total Respondents:</strong> {{ $survey->responses->count() }}</p>
    <p><strong>Description:</strong> {{ $survey->description ?? 'N/A' }}</p>

    <div style="margin-top: 50px; font-size: 10px; color: #999; text-align: center;">
        Generated by Laravel Survey Analytics Dashboard
    </div>
</body>
</html>
